### ISSUE TITLE
About the code coverage in README.md

### ISSUE THREAD

**Issue by peter279k** [Th3Mouk/YahooWeatherAPI#7]
Please fix the code coverage icon in README.md .

By the way, the badge-poser temporarily did not work because of this [issue](https://github.com/PUGX/badge-poser/issues/160) .

**Comment by Th3Mouk** [comment]
👍 I'm working on it and the release

**Comment by Th3Mouk** [comment]
Link is good, it's the github cache like each badges at each merge. Need to wait the TTL
