### ISSUE TITLE
example in README

### ISSUE THREAD

**Issue by shadiakiki1986** [Th3Mouk/YahooWeatherAPI#8]
Hi. In your readme example, you can add the following for a more complete example

```
require_once 'vendor/autoload.php';
use Th3Mouk\YahooWeatherAPI\YahooWeatherAPI;
$yahooWeather = new YahooWeatherAPI();
var_dump($yahooWeather->callApiCityName($name = 'beirut', $unit = 'c'));
```

**Comment by peter279k** [comment]
Hi @shadiakiki1986, I would like to see that you send the PR for this issue.
And we can review this PR :+1: .

Thanks.

**Comment by Th3Mouk** [comment]
Thanks @shadiakiki1986 & @peter279k I added some lines about this
